
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author radle
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public static final int MANHATTAN = 0, PYTHAGORAS = 1, STRAIGHT = 2;
    public static int selected = 1;
PopupFrame f = new PopupFrame();
   
    public Frame() {
        initComponents();
        this.setTitle("A*");
        this.setFocusable(false);
           f.setVisible(false);
           f.setFocusable(false);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DistanceGroup = new javax.swing.ButtonGroup();
        panel1 = new Panel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        TimerItem = new javax.swing.JMenuItem();
        SkipCalculateMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ValueCheckBox = new javax.swing.JCheckBoxMenuItem();
        GridCheckbox = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        randomCheckbox = new javax.swing.JCheckBoxMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        SizeMenu = new javax.swing.JMenuItem();
        SpeedMenuItem = new javax.swing.JMenuItem();
        ObstaclePMenu = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        ResetMenu = new javax.swing.JMenuItem();
        ResetA = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        ManhattenButton = new javax.swing.JRadioButtonMenuItem();
        PythagorasButton = new javax.swing.JRadioButtonMenuItem();
        GeradeButton = new javax.swing.JRadioButtonMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        ClearConsoleItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        panel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                panel1ComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        jMenu1.setText("Settings");

        TimerItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, 0));
        TimerItem.setText("StartTimer");
        TimerItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimerItemActionPerformed(evt);
            }
        });
        jMenu1.add(TimerItem);

        SkipCalculateMenu.setText("Calcaulate all");
        SkipCalculateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SkipCalculateMenuActionPerformed(evt);
            }
        });
        jMenu1.add(SkipCalculateMenu);
        jMenu1.add(jSeparator1);

        ValueCheckBox.setText("ShowValues");
        ValueCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValueCheckBoxActionPerformed(evt);
            }
        });
        jMenu1.add(ValueCheckBox);

        GridCheckbox.setSelected(true);
        GridCheckbox.setText("ShowGrid");
        GridCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GridCheckboxActionPerformed(evt);
            }
        });
        jMenu1.add(GridCheckbox);

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Diagonal");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        randomCheckbox.setText("Random");
        randomCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomCheckboxActionPerformed(evt);
            }
        });
        jMenu1.add(randomCheckbox);
        jMenu1.add(jSeparator2);

        SizeMenu.setText("Set Size");
        SizeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SizeMenuActionPerformed(evt);
            }
        });
        jMenu1.add(SizeMenu);

        SpeedMenuItem.setText("Set Speed");
        SpeedMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpeedMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(SpeedMenuItem);

        ObstaclePMenu.setText("Set obstacle p");
        ObstaclePMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObstaclePMenuActionPerformed(evt);
            }
        });
        jMenu1.add(ObstaclePMenu);
        jMenu1.add(jSeparator3);

        jMenu3.setText("Controls");

        jMenuItem1.setText("Move 1 step with \"W\"");
        jMenu3.add(jMenuItem1);

        jMenuItem3.setText("Scroll to change the type to place, shown bottom left");
        jMenu3.add(jMenuItem3);

        jMenuItem2.setText("Click to place, Shift Click to remove");
        jMenu3.add(jMenuItem2);

        jMenuItem4.setText("Reset resets all objects, Reset A* just resets the search");
        jMenu3.add(jMenuItem4);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Reset");

        ResetMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
        ResetMenu.setText("Reset");
        ResetMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetMenuActionPerformed(evt);
            }
        });
        jMenu4.add(ResetMenu);

        ResetA.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_BACK_SPACE, 0));
        ResetA.setText("ResetA*");
        ResetA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetAActionPerformed(evt);
            }
        });
        jMenu4.add(ResetA);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Properties");

        DistanceGroup.add(ManhattenButton);
        ManhattenButton.setText("Manhatten Distance");
        ManhattenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManhattenButtonActionPerformed(evt);
            }
        });
        jMenu5.add(ManhattenButton);

        DistanceGroup.add(PythagorasButton);
        PythagorasButton.setSelected(true);
        PythagorasButton.setText("Pytagroas");
        PythagorasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PythagorasButtonActionPerformed(evt);
            }
        });
        jMenu5.add(PythagorasButton);

        DistanceGroup.add(GeradeButton);
        GeradeButton.setText("Straight");
        GeradeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeradeButtonActionPerformed(evt);
            }
        });
        jMenu5.add(GeradeButton);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Console");

        jCheckBoxMenuItem2.setText("OpenConsole");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem2);
        jMenu2.add(jSeparator4);

        ClearConsoleItem.setText("Clear");
        ClearConsoleItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearConsoleItemActionPerformed(evt);
            }
        });
        jMenu2.add(ClearConsoleItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        System.out.println(jCheckBoxMenuItem1.getState());
        panel1.diagonal = jCheckBoxMenuItem1.getState();
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void ResetMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetMenuActionPerformed
        System.out.println("RESET");
        panel1.reset();
    }//GEN-LAST:event_ResetMenuActionPerformed

    private void randomCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomCheckboxActionPerformed
        panel1.randomObstacles = randomCheckbox.getState();
        panel1.randomObstacles();
    }//GEN-LAST:event_randomCheckboxActionPerformed

    private void ResetAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetAActionPerformed
        panel1.resetSolver();
    }//GEN-LAST:event_ResetAActionPerformed

    private void TimerItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimerItemActionPerformed
        panel1.timr.start();
    }//GEN-LAST:event_TimerItemActionPerformed

    private void ValueCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValueCheckBoxActionPerformed
        panel1.showValues(ValueCheckBox.getState());
    }//GEN-LAST:event_ValueCheckBoxActionPerformed

    private void PythagorasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PythagorasButtonActionPerformed
        selected = PYTHAGORAS;
        panel1.resetSolver();
    }//GEN-LAST:event_PythagorasButtonActionPerformed

    private void ManhattenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManhattenButtonActionPerformed
        selected = MANHATTAN;
        panel1.resetSolver();
    }//GEN-LAST:event_ManhattenButtonActionPerformed

    private void GeradeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeradeButtonActionPerformed
        selected = STRAIGHT;
        panel1.resetSolver();
    }//GEN-LAST:event_GeradeButtonActionPerformed

    private void SizeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SizeMenuActionPerformed
        try {
            String result = JOptionPane.showInputDialog(this, "Set the number of cols", Panel.cols);
            panel1.updateCols(Integer.parseInt(result));
        } catch (Exception e) {
        }


    }//GEN-LAST:event_SizeMenuActionPerformed

    private void SpeedMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpeedMenuItemActionPerformed
        try {
            String result = JOptionPane.showInputDialog(this, "Set the timer delay in ms", panel1.timr.getDelay());
            panel1.timr.setDelay(Integer.parseInt(result));
        } catch (Exception e) {
        }

    }//GEN-LAST:event_SpeedMenuItemActionPerformed

    private void ObstaclePMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObstaclePMenuActionPerformed
        try {
            String result = JOptionPane.showInputDialog(this, "Set the P for the obstacles", (int)(panel1.p * 100));
            panel1.p = Float.parseFloat(result) / 100;
        } catch (Exception e) {
        }

    }//GEN-LAST:event_ObstaclePMenuActionPerformed

    private void GridCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GridCheckboxActionPerformed
        panel1.showGrid = GridCheckbox.isSelected();
    }//GEN-LAST:event_GridCheckboxActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
 
      
    }//GEN-LAST:event_formComponentResized

    private void panel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panel1ComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_panel1ComponentResized

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
       f.setVisible(jCheckBoxMenuItem2.getState());
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void ClearConsoleItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearConsoleItemActionPerformed
       PopupFrame.jTextArea1.setText("");
    }//GEN-LAST:event_ClearConsoleItemActionPerformed

    private void SkipCalculateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SkipCalculateMenuActionPerformed
       panel1.skipCalculation();
    }//GEN-LAST:event_SkipCalculateMenuActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ClearConsoleItem;
    private javax.swing.ButtonGroup DistanceGroup;
    private javax.swing.JRadioButtonMenuItem GeradeButton;
    private javax.swing.JCheckBoxMenuItem GridCheckbox;
    private javax.swing.JRadioButtonMenuItem ManhattenButton;
    private javax.swing.JMenuItem ObstaclePMenu;
    private javax.swing.JRadioButtonMenuItem PythagorasButton;
    private javax.swing.JMenuItem ResetA;
    private javax.swing.JMenuItem ResetMenu;
    private javax.swing.JMenuItem SizeMenu;
    private javax.swing.JMenuItem SkipCalculateMenu;
    private javax.swing.JMenuItem SpeedMenuItem;
    private javax.swing.JMenuItem TimerItem;
    private javax.swing.JCheckBoxMenuItem ValueCheckBox;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private Panel panel1;
    private javax.swing.JCheckBoxMenuItem randomCheckbox;
    // End of variables declaration//GEN-END:variables
}
